import SceneOne from '../img/scene-1.svg';
import SceneTwo from '../img/scene-2.svg';

export const COUNTRIES = [
	{
		name: 'USA',
		count: 10,
		events: [
			{
				name: 'Azent Overseas Education Online Fair A - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair B - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair C - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair D - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair E - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair F - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair G - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair H - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair I - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair J - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
		],
	},
	{
		name: 'UK',
		count: 3,
		events: [
			{
				name: 'Azent Overseas Education Online Fair A - UK',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair B - UK',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair C - UK',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
		],
	},
	{
		name: 'Canada',
		count: 8,
		events: [
			{
				name: 'Azent Overseas Education Online Fair A - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair B - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair C - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair D - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair E - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair F - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair G - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair H - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
		],
	},
	{
		name: 'Australia',
		count: 15,
		events: [
			{
				name: 'Azent Overseas Education Online Fair A - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair B - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair C - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair D - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair E - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair F - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair G - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair H - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair I - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair J - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair K - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair L - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair M - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
			{
				name: 'Azent Overseas Education Online Fair N - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneTwo,
			},
			{
				name: 'Azent Overseas Education Online Fair O - USA',
				date: '10th May 2021',
				venue: 'Zoom Meet',
				time: '02:00 PM',
				thumbnail: SceneOne,
			},
		],
	},
	{
		name: 'New Zealand',
		count: 0,
		events: [],
	},
	{
		name: 'Singapore',
		count: 0,
		events: [],
	},
	{
		name: 'Ireland',
		count: 0,
		events: [],
	},
	{
		name: 'Germany',
		count: 0,
		events: [],
	},
	{
		name: 'Spain',
		count: 0,
		events: [],
	},
	{
		name: 'London',
		count: 0,
		events: [],
	},
];
